kind: pipeline
type: docker
name: default

steps:
  - name: Go lint
    image: golangci/golangci-lint:v1.49-alpine
    environment:
      GOLANGCI_LINT_CACHE: "/drone/src/.cache/golangci-lint"
    commands:
      - golangci-lint cache status
      - golangci-lint run --timeout 3m0s
    when:
      branch:
        exclude:
          - "master"
          - "*stable"

  - name: Rebuild lint cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
    - name: golint-cache
      path: /golint-cache
    settings:
      rebuild: true
      mount:
      - .cache/golangci-lint
    when:
      branch:
        exclude:
          - "master"
          - "*stable"

  - name: Bump and tag
    image: golang:1.18
    environment:
      GITHUB_API_KEY:
        from_secret: gh_api_key
      GITHUB_API_USER:
        from_secret: gh_api_user
    commands:
      - go install github.com/guilhem/bump@v0.2.1
      - git remote add authenticated-origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/$DRONE_REPO
      - git fetch --tags authenticated-origin
      - bump patch --allow-dirty
      - git push authenticated-origin --tags
    when:
      branch:
        - master

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: publish

steps:
  - name: Build and publish
    image: golang:1.18
    environment:
      GO111MODULE: on
      GITHUB_API_KEY:
        from_secret: gh_api_key
    commands:
      - echo $DRONE_TAG | grep -v / || exit 78 # Skip if submodule is tagged
      - go mod download
      - make build
      - go install github.com/tcnksm/ghr@v0.15.0
      - ghr -t $GITHUB_API_KEY -u ${DRONE_REPO_NAMESPACE} -r ${DRONE_REPO_NAME} -c ${DRONE_COMMIT} -delete ${DRONE_TAG} ./bin

trigger:
  event:
    - tag
